-- MySQL Script generated by MySQL Workbench
-- Fri Dec 28 09:45:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema service_center
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service_center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service_center` DEFAULT CHARACTER SET utf8 ;
USE `service_center` ;

-- -----------------------------------------------------
-- Table `service_center`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(250) NULL,
  `telephone` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `customer_id` INT NULL,
  `user_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_client1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_user_client1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `service_center`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_manufacturer_idx` (`manufacturer_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_product_manufacturer`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `service_center`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`part_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`part_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`part` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `part_category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_part_part_type1_idx` (`part_category_id` ASC),
  INDEX `fk_part_product1_idx` (`product_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_part_part_type1`
    FOREIGN KEY (`part_category_id`)
    REFERENCES `service_center`.`part_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_part_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `service_center`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`order_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`order_job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `code` VARCHAR(10) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`service_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`service_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repair_status` VARCHAR(10) NULL,
  `code` VARCHAR(45) NULL,
  `date_order` DATE NULL,
  `product_id` INT NOT NULL,
  `check_serial` TINYINT NULL,
  `serial` VARCHAR(45) NULL,
  `customer_id` INT NULL,
  `client_fault` VARCHAR(500) NULL,
  `comment` VARCHAR(500) NULL,
  `engineer_descr` VARCHAR(500) NULL,
  `date_expected` DATE NULL,
  `expected_cost` DOUBLE NOT NULL,
  `prepaid` DOUBLE NOT NULL,
  `final_price` DOUBLE NOT NULL,
  `date_finish` DATE NULL,
  `date_warranty` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_service_order_product1_idx` (`product_id` ASC),
  INDEX `fk_service_order_client1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_service_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `service_center`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_client1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `service_center`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`service_order_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`service_order_job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `order_job_id` INT NOT NULL,
  `final_price` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_service_order_job_service_order1_idx` (`service_order_id` ASC),
  INDEX `fk_service_order_job_user1_idx` (`user_id` ASC),
  INDEX `fk_service_order_job_order_job1_idx` (`order_job_id` ASC),
  CONSTRAINT `fk_service_order_job_service_order1`
    FOREIGN KEY (`service_order_id`)
    REFERENCES `service_center`.`service_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_job_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `service_center`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_job_order_job1`
    FOREIGN KEY (`order_job_id`)
    REFERENCES `service_center`.`order_job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`user_login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`user_login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_login_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_login_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `service_center`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NULL,
  `part_id` INT NOT NULL,
  `count` DOUBLE NULL,
  `price_per_one` DOUBLE NULL,
  `descr` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_warehouse_part1_idx` (`part_id` ASC),
  CONSTRAINT `fk_warehouse_part1`
    FOREIGN KEY (`part_id`)
    REFERENCES `service_center`.`part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_center`.`service_order_part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_center`.`service_order_part` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NULL,
  `service_order_id` INT NOT NULL,
  `final_price` DOUBLE NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_service_order_part_warehouse1_idx` (`warehouse_id` ASC),
  INDEX `fk_service_order_part_service_order1_idx` (`service_order_id` ASC),
  INDEX `fk_service_order_part_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_service_order_part_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `service_center`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_part_service_order1`
    FOREIGN KEY (`service_order_id`)
    REFERENCES `service_center`.`service_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_part_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `service_center`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
